//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyTableDataLayer.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bookmytableEntities : DbContext
    {
        public bookmytableEntities()
            : base("name=bookmytableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HotelDetail> HotelDetails { get; set; }
        public virtual DbSet<HotelDiningDetail> HotelDiningDetails { get; set; }
        public virtual DbSet<HotelMenuTable> HotelMenuTables { get; set; }
        public virtual DbSet<CustomerTable> CustomerTables { get; set; }
        public virtual DbSet<MenuDishTable> MenuDishTables { get; set; }
        public virtual DbSet<salesOrderItemTable> salesOrderItemTables { get; set; }
        public virtual DbSet<salesOrderTable> salesOrderTables { get; set; }
        public virtual DbSet<OrderMenuEntity> OrderMenuEntities { get; set; }
        public virtual DbSet<OrderPaymentDetail> OrderPaymentDetails { get; set; }
    
        public virtual ObjectResult<pSp_GetHotelDiningDetails_Result> pSp_GetHotelDiningDetails(Nullable<int> hotelId)
        {
            var hotelIdParameter = hotelId.HasValue ?
                new ObjectParameter("HotelId", hotelId) :
                new ObjectParameter("HotelId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pSp_GetHotelDiningDetails_Result>("pSp_GetHotelDiningDetails", hotelIdParameter);
        }
    
        public virtual ObjectResult<pSp_GetHotelMEnuDetails_Result> pSp_GetHotelMEnuDetails(Nullable<int> hotelId)
        {
            var hotelIdParameter = hotelId.HasValue ?
                new ObjectParameter("HotelId", hotelId) :
                new ObjectParameter("HotelId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pSp_GetHotelMEnuDetails_Result>("pSp_GetHotelMEnuDetails", hotelIdParameter);
        }
    
        public virtual ObjectResult<pSp_GetRestaurantsDetails_Result> pSp_GetRestaurantsDetails(Nullable<int> vch_IsActive)
        {
            var vch_IsActiveParameter = vch_IsActive.HasValue ?
                new ObjectParameter("Vch_IsActive", vch_IsActive) :
                new ObjectParameter("Vch_IsActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pSp_GetRestaurantsDetails_Result>("pSp_GetRestaurantsDetails", vch_IsActiveParameter);
        }
    
        public virtual ObjectResult<AddBookMyTableAndMenuOrder_Result> AddBookMyTableAndMenuOrder(Nullable<int> p_intHotelId, Nullable<int> p_intTableBookingID, Nullable<int> p_intTotalQuantity, Nullable<decimal> p_dcmlTotalAmt, string p_vchApprovalName, string p_vchCustomerName, string p_vchPhoneNumber, string p_vchEmailID, string p_vchCity, string p_vchCountry, string p_vchAddress)
        {
            var p_intHotelIdParameter = p_intHotelId.HasValue ?
                new ObjectParameter("p_intHotelId", p_intHotelId) :
                new ObjectParameter("p_intHotelId", typeof(int));
    
            var p_intTableBookingIDParameter = p_intTableBookingID.HasValue ?
                new ObjectParameter("P_intTableBookingID", p_intTableBookingID) :
                new ObjectParameter("P_intTableBookingID", typeof(int));
    
            var p_intTotalQuantityParameter = p_intTotalQuantity.HasValue ?
                new ObjectParameter("P_intTotalQuantity", p_intTotalQuantity) :
                new ObjectParameter("P_intTotalQuantity", typeof(int));
    
            var p_dcmlTotalAmtParameter = p_dcmlTotalAmt.HasValue ?
                new ObjectParameter("P_dcmlTotalAmt", p_dcmlTotalAmt) :
                new ObjectParameter("P_dcmlTotalAmt", typeof(decimal));
    
            var p_vchApprovalNameParameter = p_vchApprovalName != null ?
                new ObjectParameter("p_vchApprovalName", p_vchApprovalName) :
                new ObjectParameter("p_vchApprovalName", typeof(string));
    
            var p_vchCustomerNameParameter = p_vchCustomerName != null ?
                new ObjectParameter("p_vchCustomerName", p_vchCustomerName) :
                new ObjectParameter("p_vchCustomerName", typeof(string));
    
            var p_vchPhoneNumberParameter = p_vchPhoneNumber != null ?
                new ObjectParameter("p_vchPhoneNumber", p_vchPhoneNumber) :
                new ObjectParameter("p_vchPhoneNumber", typeof(string));
    
            var p_vchEmailIDParameter = p_vchEmailID != null ?
                new ObjectParameter("p_vchEmailID", p_vchEmailID) :
                new ObjectParameter("p_vchEmailID", typeof(string));
    
            var p_vchCityParameter = p_vchCity != null ?
                new ObjectParameter("p_vchCity", p_vchCity) :
                new ObjectParameter("p_vchCity", typeof(string));
    
            var p_vchCountryParameter = p_vchCountry != null ?
                new ObjectParameter("p_vchCountry", p_vchCountry) :
                new ObjectParameter("p_vchCountry", typeof(string));
    
            var p_vchAddressParameter = p_vchAddress != null ?
                new ObjectParameter("p_vchAddress", p_vchAddress) :
                new ObjectParameter("p_vchAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AddBookMyTableAndMenuOrder_Result>("AddBookMyTableAndMenuOrder", p_intHotelIdParameter, p_intTableBookingIDParameter, p_intTotalQuantityParameter, p_dcmlTotalAmtParameter, p_vchApprovalNameParameter, p_vchCustomerNameParameter, p_vchPhoneNumberParameter, p_vchEmailIDParameter, p_vchCityParameter, p_vchCountryParameter, p_vchAddressParameter);
        }
    
        public virtual int AddsalesOrderItemTable(Nullable<int> p_intHotelId, Nullable<int> p_intMenuID, Nullable<int> p_intTableId, Nullable<decimal> p_dcmlTotalAmt, Nullable<int> p_OrderId, Nullable<int> p_intQuantity, string p_vchDishName)
        {
            var p_intHotelIdParameter = p_intHotelId.HasValue ?
                new ObjectParameter("p_intHotelId", p_intHotelId) :
                new ObjectParameter("p_intHotelId", typeof(int));
    
            var p_intMenuIDParameter = p_intMenuID.HasValue ?
                new ObjectParameter("p_intMenuID", p_intMenuID) :
                new ObjectParameter("p_intMenuID", typeof(int));
    
            var p_intTableIdParameter = p_intTableId.HasValue ?
                new ObjectParameter("P_intTableId", p_intTableId) :
                new ObjectParameter("P_intTableId", typeof(int));
    
            var p_dcmlTotalAmtParameter = p_dcmlTotalAmt.HasValue ?
                new ObjectParameter("P_dcmlTotalAmt", p_dcmlTotalAmt) :
                new ObjectParameter("P_dcmlTotalAmt", typeof(decimal));
    
            var p_OrderIdParameter = p_OrderId.HasValue ?
                new ObjectParameter("p_OrderId", p_OrderId) :
                new ObjectParameter("p_OrderId", typeof(int));
    
            var p_intQuantityParameter = p_intQuantity.HasValue ?
                new ObjectParameter("P_intQuantity", p_intQuantity) :
                new ObjectParameter("P_intQuantity", typeof(int));
    
            var p_vchDishNameParameter = p_vchDishName != null ?
                new ObjectParameter("p_vchDishName", p_vchDishName) :
                new ObjectParameter("p_vchDishName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddsalesOrderItemTable", p_intHotelIdParameter, p_intMenuIDParameter, p_intTableIdParameter, p_dcmlTotalAmtParameter, p_OrderIdParameter, p_intQuantityParameter, p_vchDishNameParameter);
        }
    
        public virtual ObjectResult<Sp_GetOrderDetails_Result> Sp_GetOrderDetails(Nullable<int> orderID)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetOrderDetails_Result>("Sp_GetOrderDetails", orderIDParameter);
        }
    
        public virtual ObjectResult<Sp_GetOrderDetailsToEmployee_Result> Sp_GetOrderDetailsToEmployee(Nullable<int> employeeID, Nullable<int> roleID)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetOrderDetailsToEmployee_Result>("Sp_GetOrderDetailsToEmployee", employeeIDParameter, roleIDParameter);
        }
    
        public virtual ObjectResult<Sp_GetUserAndUserRoleDetails_Result> Sp_GetUserAndUserRoleDetails(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetUserAndUserRoleDetails_Result>("Sp_GetUserAndUserRoleDetails", userNameParameter, passwordParameter);
        }
    }
}
