//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyTableDataLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelDetail()
        {
            this.HotelDiningDetails = new HashSet<HotelDiningDetail>();
            this.MenuDishTables = new HashSet<MenuDishTable>();
        }
    
        public int Id { get; set; }
        public string HotelName { get; set; }
        public string ContactPersoneName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<int> Rating { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailID { get; set; }
        public string OpenintHours { get; set; }
        public string HotelType { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte[] ts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelDiningDetail> HotelDiningDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuDishTable> MenuDishTables { get; set; }
    }
}
