//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyTableDataLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMenuEntity
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<int> DishId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string DishName { get; set; }
        public Nullable<decimal> DishAmount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public byte[] ts { get; set; }
    }
}
